version: '3.9'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: ./
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MONGODB_URI: "mongodb://root:example@db:27017/"
